//! Gray code generation
//!
//! This module provides functionality for generating Gray codes, which are
//! binary number systems where consecutive values differ by only one bit.
//!
//! ## Key Functions
//!
//! - [`brgc_gen`] - Generate binary reflected Gray code sequence
//!
//! ## Algorithm
//!
//! The binary reflected Gray code (BRGC) is generated recursively. For n bits,
//! the sequence is generated by: 1) recursively generating the (n-1)-bit sequence,
//! 2) adding the highest-order bit (0) to those, 3) adding the highest-order bit (1)
//! to the reversed (n-1)-bit sequence.
//!
//! This produces a sequence of 2^n code words where each successive word differs
//! by exactly one bit.
//!
//! ## Reference
//!
//! Gray codes were originally designed by Frank Gray (1953) for pulse code modulation.
//!
//! ## Complexity
//!
//! - `brgc_gen(n)`: O(2^n) output size, O(n) stack space

use genawaiter::sync::{Gen, GenBoxed};

/// The `brgc_gen` function generates a binary reflexed gray code sequence of length `n`.
///
/// Binary reflected Gray code (BRGC) for $n$ bits:
///
/// $$ G(n) = 0 \cdot G(n-1) \oplus 1 \cdot G(n-1)^R $$
///
/// where $G(n-1)^R$ is the reverse of the $(n-1)$-bit sequence.
///
/// Arguments:
///
/// * `n`: The parameter `n` represents the number of bits in the binary reflexed gray code sequence.
///
/// Returns:
///
/// The function `brgc_gen` returns a `GenBoxed<usize>`, which is a boxed generator that yields values
/// of type `usize`.
///
/// # Examples
///
/// ```
/// use ecgen::brgc_gen;
///
/// let mut lst = ["⬜"; 3];
/// println!("{}", lst.concat());
/// let mut cnt = 1;
/// for n in brgc_gen(lst.len()) {
///     lst[n] = if lst[n] == "⬜" { "⬛" } else { "⬜" };
///     println!("{}", lst.concat());
///     cnt += 1;
/// }
///
/// assert_eq!(cnt, 8);
/// ```
pub fn brgc_gen(n: usize) -> GenBoxed<usize> {
    Gen::new_boxed(|co| async move {
        if n < 1 {
            return;
        }
        for i in brgc_gen(n - 1) {
            co.yield_(i).await;
        }
        co.yield_(n - 1).await;
        for i in brgc_gen(n - 1) {
            co.yield_(i).await;
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_brgc() {
        let mut cnt = 1;
        for _n in brgc_gen(3) {
            cnt += 1;
        }
        assert_eq!(cnt, 8);
    }
}
